package com.company.taskmanager.models.comment;

import com.company.taskmanager.models.task.Task;
import com.company.taskmanager.models.user.User;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Table(name = "comments")
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Comment {

    /**
     * Unique identifier for the comment.
     * <p>
     * This is the primary key of the comment entity, automatically generated by the database.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    /**
     * Text content of the comment.
     * <p>
     * This field stores the actual content or message of the comment.
     * </p>
     */
    @Column(name = "text")
    private String text;

    /**
     * The task associated with this comment.
     * <p>
     * This is a many-to-one relationship with the {@link Task} entity.
     * Indicates the task to which the comment is related.
     * </p>
     *
     * @see Task
     */
    @ManyToOne
    @JoinColumn(name = "task_id", nullable = false)
    private Task task;

    /**
     * The user who made this comment.
     * <p>
     * This is a many-to-one relationship with the {@link User} entity.
     * Indicates the user who authored the comment.
     * </p>
     *
     * @see User
     */
    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

}
